version: '2.1'

services:
  gadget:
    image: pipex/gadget:v0.1.2
    restart: on-failure
    # Needed to have access to the host network
    network_mode: host
    cap_add:
      # Needed to load kernel modules
      - SYS_MODULE
      # Needed to configure network
      - NET_ADMIN
    labels:
      # Needed for access to the host `/lib/modules` directory
      io.balena.features.kernel-modules: '1'
      # Needed for access to the host `/sys` directory
      io.balena.features.sysfs: '1'
  
  fanshim:
    image: bh.cr/gh_pipex/fanshim 
    restart: always
    devices:
      # Required to access gpio 
      - /dev/gpiomem
    labels:
      # Required to access the host /proc directory
      io.balena.features.procfs: '1'

  sweet-home:
    image: pipex/sweet-home:v0.6.8
    command: sleep infinity # allows the container to run as a daemon
    restart: always
    environment:
      # This is to prevent the Balena supervisor from overriding this value to
      # ensure the right one is used. Do not change this as
      # it has no effect on the runtime username
      USER: 'me'
      # Setting the TZ env var allows for the local date
      # to be shown in tmux and as result of the `date` command
      TZ: 'America/Santiago'
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-socket: '1'
    volumes:
      - home:/home/me # Keep home files accross container restarts
      - pkgs:/nix # Keep package configuration accross container restarts

volumes:
  home:
  pkgs:
